Repository HathorNetwork/hathor-wallet, pull requests merged in 2022-05, with the labels that each got.

#292 feat: wallet service integration on the desktop wallet
  locale/texts.pot
  package-lock.json
  package.json
  src/actions/index.js
  src/components/ModalSendTx.js
  src/components/SendTxHandler.js
  src/components/TokenAdministrative.js
  src/components/TokenGeneralInfo.js
  src/components/TokenHistory.js
  src/components/WalletAddress.js
  src/components/tokens/TokenDelegate.js
  src/components/tokens/TokenDestroy.js
  src/components/tokens/TokenMelt.js
  src/components/tokens/TokenMint.js
  src/constants.js
  src/featureFlags.js
  src/index.scss
  src/reducers/index.js
  src/screens/CreateNFT.js
  src/screens/CreateToken.js
  src/screens/LockedWallet.js
  src/screens/SendTokens.js
  src/screens/Settings.js
  src/screens/Wallet.js
  src/utils/helpers.js
  src/utils/wallet.js
Labels: enhancement

#307 feat: wallet service change server
  locale/texts.pot
  package-lock.json
  package.json
  src/App.js
  src/constants.js
  src/index.scss
  src/reducers/index.js
  src/screens/Server.js
  src/screens/Settings.js
  src/utils/version.js
  src/utils/wallet.js
Labels: enhancement

#312 fix: issues preventing QA from passing on the current dev branch
  src/screens/Server.js
Labels: bug

#310 feat: always show tokens
  locale/texts.pot
  src/components/ModalAddManyTokens.js
  src/components/ModalAddToken.js
  src/components/TokenBar.js
  src/components/TokenGeneralInfo.js
  src/screens/CustomTokens.js
  src/screens/UnknownTokens.js
  src/screens/Wallet.js
  src/utils/wallet.js
Labels: enhancement

#309 feat: option to hide zero-balance tokens
  locale/texts.pot
  src/components/ModalAddManyTokens.js
  src/components/ModalAddToken.js
  src/components/TokenBar.js
  src/components/TokenGeneralInfo.js
  src/screens/CustomTokens.js
  src/screens/Settings.js
  src/screens/UnknownTokens.js
  src/screens/Wallet.js
  src/utils/wallet.js
Labels: enhancement

#314 Fix/minor warnings and errors
  src/components/ModalAddManyTokens.js
  src/components/ModalAddToken.js
  src/screens/SendTokens.js
Labels: bug

#313 Docs/Update QA for "hide zero balance tokens" feature
  QA.md
Labels: tests

#317 fix: hide feature should be off by default
  locale/texts.pot
  src/components/InputNumber.js
  src/components/ModalAddManyTokens.js
  src/components/ModalAddToken.js
  src/components/TokenGeneralInfo.js
  src/utils/wallet.js
Labels: bug
