Repository HathorNetwork/hathor-wallet, pull requests merged in 2023-04, with the labels that each got.

#395 fix: issues found on QA
  .github/workflows/e2e.yml
  src/__tests__/components/ModalSendTx.test.js
  src/components/ModalAddToken.js
  src/components/ModalSendTx.js
  src/screens/SentryPermission.js
  src/screens/Server.js
Labels: bug

#397 chore: bump to v0.26.0
  package-lock.json
  package.json
  public/electron.js
  src/constants.js
Labels: enhancement

#398 Release v0.26.0
  .github/workflows/e2e.yml
  package-lock.json
  package.json
  public/electron.js
  src/App.js
  src/__tests__/components/ModalPin.test.js
  src/__tests__/components/ModalSendTx.test.js
  src/actions/index.js
  src/components/GlobalModal.js
  src/components/ModalAddToken.js
  src/components/ModalPin.js
  src/components/ModalSendTx.js
  src/components/Navigation.js
  src/components/PinInput.js
  src/components/SendTxHandler.js
  src/components/atomic-swap/ExternalChangeModal.js
  src/components/atomic-swap/ModalAtomicReceive.js
  src/components/atomic-swap/ModalAtomicSend.js
  src/components/atomic-swap/ProposalBalanceTable.js
  src/components/tokens/TokenAction.js
  src/constants.js
  src/featureFlags.js
  src/index.scss
  src/reducers/index.js
  src/sagas/atomicSwap.js
  src/sagas/index.js
  src/sagas/tokens.js
  src/sagas/wallet.js
  src/screens/CreateNFT.js
  src/screens/CreateToken.js
  src/screens/SendTokens.js
  src/screens/SentryPermission.js
  src/screens/Server.js
  src/screens/atomic-swap/EditSwap.js
  src/screens/atomic-swap/ImportExisting.js
  src/screens/atomic-swap/NewSwap.js
  src/screens/atomic-swap/ProposalList.js
  src/utils/atomicSwap.js
  src/utils/helpers.js
  src/utils/wallet.js
Labels: enhancement

#399 refactor: feature toggle is now a saga
  .envrc
  .gitignore
  flake.lock
  flake.nix
  src/actions/index.js
  src/components/ModalUnhandledError.js
  src/constants.js
  src/featureFlags.js
  src/reducers/index.js
  src/sagas/featureToggle.js
  src/sagas/helpers.js
  src/sagas/index.js
  src/sagas/wallet.js
  src/screens/LockedWallet.js
  src/screens/Settings.js
  src/screens/WalletVersionError.js
  src/utils/wallet.js
Labels: enhancement

#401 refactor: proposal token channel
  src/sagas/tokens.js
Labels: refactor
