Repository HathorNetwork/hathor-wallet, pull requests merged in 2023-12, with the labels that each got.

#426 Chore: Update `react-scripts` to v4
  package-lock.json
  package.json
  src/__tests__/components/ModalSendTx.test.js
Labels: dependencies

#448 Chore: Update `electron`
  README.md
  package-lock.json
  package.json
  public/electron.js
Labels: dependencies

#449 Chore: Update to React `v18`
  package-lock.json
  package.json
  src/__tests__/components/ModalPin.test.js
  src/__tests__/components/ModalSendTx.test.js
  src/__tests__/components/PinPasswordWrapper.test.js
Labels: dependencies

#453 Fixes #443 - Automatically removes whitespaces from Addresses
  src/components/SendTokensOne.js
Labels: enhancement

#458 Chore: Update `unleash-proxy-client`
  package-lock.json
  package.json
Labels: dependencies

#461 Refactor: Navigation root for Router v5
  src/ErrorWrapper.js
  src/index.js
  src/screens/LoadWallet.js
Labels: refactor
