Repository HathorNetwork/hathor-wallet, pull requests merged in 2024-01, with the labels that each got.

#468 Refactor: Route `children` for welcome screens
  locale/texts.pot
  src/App.js
  src/components/BackButton.js
  src/components/RequestError.js
  src/components/TxRow.js
  src/components/WaitVersion.js
  src/screens/ChoosePassphrase.js
  src/screens/CreateNFT.js
  src/screens/CreateToken.js
  src/screens/CustomTokens.js
  src/screens/LoadingAddresses.js
  src/screens/LockedWallet.js
  src/screens/NFTList.js
  src/screens/Page404.js
  src/screens/SendTokens.js
  src/screens/SentryPermission.js
  src/screens/Settings.js
  src/screens/TransactionDetail.js
  src/screens/UnknownTokens.js
  src/screens/Wallet.js
  src/screens/Welcome.js
  src/screens/atomic-swap/EditSwap.js
  src/screens/atomic-swap/ImportExisting.js
  src/screens/atomic-swap/NewSwap.js
  src/screens/atomic-swap/ProposalList.js
Labels: refactor

#469 Refactor: Locked screen functional component
  src/App.js
  src/components/Navigation.js
  src/screens/LockedWallet.js
  src/screens/WalletVersionError.js
Labels: refactor

#486 Chore: Update `qrcode`
  package-lock.json
  package.json
Labels: dependencies

#483 refactor: `SendTokens` screen to functional component
  src/screens/SendTokens.js
Labels: refactor

#472 Refactor: New wallet screens to functional components
  src/components/SoftwareWalletWarningMessage.js
  src/screens/LoadWallet.js
  src/screens/NewWallet.js
  src/screens/Signin.js
  src/screens/SoftwareWalletWarning.js
  src/screens/StartHardwareWallet.js
  src/screens/WalletType.js
Labels: refactor

#475 Refactor: Admin screens to functional components
  locale/texts.pot
  src/screens/AddressList.js
  src/screens/ChoosePassphrase.js
  src/screens/Server.js
  src/screens/Settings.js
  src/screens/TransactionDetail.js
Labels: refactor

#476 Refactor: Custom token screens to functional components
  locale/texts.pot
  src/screens/CreateNFT.js
  src/screens/CreateToken.js
  src/screens/CustomTokens.js
  src/screens/NFTList.js
  src/screens/UnknownTokens.js
  src/utils/wallet.js
Labels: refactor

#496 chore: add libusb1 to flake
  flake.nix
Labels: enhancement

#495 feat: send app version
  src/sagas/featureToggle.js
Labels: enhancement
