Repository HathorNetwork/hathor-wallet, pull requests merged in 2024-02, with the labels that each got.

#497 fix: forceful quit
  src/App.js
  src/ErrorWrapper.js
  src/components/ModalUnhandledError.js
Labels: bug

#488 Refactor: `wallet` screen to functional component
  src/screens/Wallet.js
Labels: refactor

#501 chore: Upgrade to NodeJS 20
  .github/workflows/e2e.yml
  .github/workflows/main.yml
  .nvmrc
  ELECTRON.md
  README.md
  package.json
Labels: dependencies

#503 chore: Upgrades `jQuery`
  package-lock.json
  package.json
Labels: dependencies

#521 chore: Removes `typescript`
  package-lock.json
  package.json
Labels: dependencies

#515 chore: Upgrades `nodemon`
  package-lock.json
  package.json
Labels: dependencies

#519 chore: Upgrades `sass`
  package-lock.json
  package.json
Labels: dependencies

#506 chore: Upgrades `react-paginate`
  package-lock.json
  package.json
Labels: dependencies

#505 chore: Upgrades `ttag`
  package-lock.json
  package.json
Labels: dependencies

#514 chore: Upgrades `sentry`
  package-lock.json
  package.json
Labels: dependencies

#513 chore: Upgrades `jsdoc`
  package-lock.json
  package.json
Labels: dependencies

#510 fix: Accessing colors from `scss`
  package.json
  src/components/Loading.js
  src/components/ModalSendTx.js
  src/components/TokenHistory.js
  src/components/tokens/TokenAction.js
  src/components/tokens/TokenMelt.js
  src/constants.js
  src/index.module.scss
  src/screens/LoadingAddresses.js
  src/screens/LockedWallet.js
  src/screens/SendTokens.js
  src/screens/Server.js
  src/screens/TransactionDetail.js
  src/screens/Wallet.js
Labels: bug
